---
- hosts: workstation
 -tasks
   - name: 'Add some depos'
     action: apt_repository: repo='{{item}}'
     with_itmes:
       - ppa:webupd8team/java
       - ppa:webupd8team/sublime-text-3
       - ppa:webupd8team/themes
       - ppa:linrunner/tlp
       
   - name: 'install programs'
     action: apt pkg={{item}} state=present
     with_items:
      - build-essential
      - curl
      - git-core
      - sqlite3
      - autoconf
      - automake
      - git
      - aptitude
      - vim
      - vim-addon-manager
      - vim-gnome
      - vim-gtk
      - vim-scripts
      - vim-youcompleteme 
      - thunar-vcs-plugin
      - xfce4-clipman
      - shiki-colors-xfwm-theme
      - ubuntu-restricted-extras
      - flashplugin-installer
      - vlc
      - libdvdread4       
      - oracle-java8-installer
      - sublime-text-installer
      - tlp
      - tlp-rdw
      - spotify-client
      
/usr/share/doc/libdvdread4/install-css.sh
