---
- hosts: workstation
 
  tasks:
   - name: 'install programs'
     action: apt pkg={{item}} state=present
     with_items:
      - build-essential
      - curl
      - git-core
      - sqlite3
      - autoconf
      - automake
      - git
      - aptitude
      - vim
      - vim-addon-manager
      - vim-gnome
      - vim-gtk
      - vim-scripts
      - vim-youcompleteme 
      - thunar-vcs-plugin
      - xfce4-clipman
      - shiki-colors-xfwm-theme 
      
