---
- hosts: workstation

  tasks:
 
   - name: 'Add google dep keys'
     action: apt_key url='https://dl.google.com/linux/linux_signing_key.pub' state=present
     with_items:
        - 'http://keyserver.ubuntu.com'

   - name: 'Add spotify dep keys'
     action: apt_key url='http://keyserver.ubuntu.com' state=present id=94558F59

   - name: 'Add some depos'
     action: apt_repository repo='{{item}}'
     with_items:
       - ppa:webupd8team/java
       - ppa:webupd8team/sublime-text-3
       - ppa:webupd8team/themes
       - ppa:linrunner/tlp
       - "deb http://repository.spotify.com stable non-free"
       
   - name: 'install programs'
     action: apt pkg={{item}} state=present  update_cache=yes upgrade=yes
     with_items:
      - build-essential
      - curl
      - git-core
      - sqlite3
      - autoconf
      - automake
      - git
      - aptitude
      - vim
      - vim-addon-manager
      - vim-gnome
      - vim-gtk
      - vim-scripts
      - vim-youcompleteme 
      - thunar-vcs-plugin
      - xfce4-clipman
      - shiki-colors-xfwm-theme
      - ubuntu-restricted-extras
      - flashplugin-installer
      - vlc
      - libdvdread4       
      - oracle-java8-installer
      - sublime-text-installer
      - tlp
      - tlp-rdw
      - spotify-client
      - htop
      - nmap
      - gitx
      - libreoffice
      - ffmpeg
      - "https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb"
      - "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      
  - name: 'Finish installing dcss'
    sudo: yes
    command: '/usr/share/doc/libdvdread4/install-css.sh'
    
  - name: 'Finish installing tlp'
    sudo: yes
    command: 'tlp start'


# EOF ###########################################################
