# config.yml #####################################################################
---
sources:
  local:
    #- playbook.yml

  url:
    #- name: playbook.yml
    #  url: https://db.tt/VcyI9dvr

  git:
    - name: 'ubunutu'
      repo: 'https://github.com/NeuromaticSystems/ansible-ubuntu.git'
      playbooks:
         # ADD BACK BEFORE DOING FRESH INSTALL JUST DEBUGGING apt.yml- pip.yml
         - apt.yml
         # ADD BACK BEFORE DOING FRESH INSTALL JUST DEBUGGING apt.yml- java8.yml
         # ADD BACK BEFORE DOING FRESH INSTALL JUST DEBUGGING apt.yml- ssh-key.yml
         #- Development.yml
         #- conf_and_bin.yml
         #- pycharm
         #- lastpass
         #- mackup.yml
         #- dropbox.yml
         #- intellij-idea-ultimate.yml
         #- skype.yml
         #- vagrant.yml
         #- virtualbox.yml
         #- spideroak

# EOF ###########################################################################
