# config.yml #####################################################################
---
sources:
  local:
    #- playbook.yml

  url:
    #- name: playbook.yml
    #  url: https://db.tt/VcyI9dvr

  git:
    - name: 'ubunutu'
      repo: 'https://github.com/NeuromaticSystems/ansible-ubuntu.git'
      playbooks:
         #- pip.yml
         #- Development.yml
         #- conf_and_bin.yml
         #- mackup.yml
         #- dropbox.yml
         #- gitx.yml
         #- intellij-idea-ultimate.yml
         #- java8.yml
         #- libreoffice.yml
         #- skype.yml
         #- vagrant.yml
         #- virtualbox.yml

# EOF ###########################################################################
