# https://github.com/mhamrah/ansible-java8/blob/master/tasks/main.yml

#- name: add webupd8team
#  shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu {{ ansible_distribution_release }} main" | tee -a /etc/apt/sources.list
#  sudo: yes

#- name: add key server
#  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
#  sudo: yes

---
- hosts: workstation

  tasks:
    - name: add add-apt-repostory
      action: apt pkg=software-properties-common state=present update_cache=yes
      sudo: yes 
    
    - name: add add-apt-repostory
      action: apt pkg=python-software-properties state=present update_cache=yes
      sudo: yes 
      when: ansible_distribution_release == "precise"

    - name: add webupd8 ppa
      action: apt_repository repo='ppa:webupd8team/java'

    - name: update
      action: apt update_cache=yes
      sudo: yes

    - name: auto accept oracle jdk license
      action: shell echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: install java8
      action: shell apt-get install -y oracle-java8-installer ca-certificates
      sudo: yes
