---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in pip.yml"

    - name: install apps from pip
      pip: name={{item}}
      sudo: yes
      with_items:
          - virtualenv
          - virtualenvwrapper
          - pyyaml
          - awscli

