---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in pip.yml"

    - name: install apps from pip
      pip: name={{item}}
      sudo: yes
      with_items:
          - cookiecutter
          - tox
          - virtualenv
          - virtualenvwrapper
          - pyyaml
          - awscli
          - virtualenv
          - virtualenvwrapper
          #- bpython
          - mackup
          - thefuck
          - flake8
          - pythong
          - pipsi
          #- Fabric
          #- Flask
          #- Jinja2
          #- SQLAlchemy
          #- Sphinx
          #- Werkzeug
          #- boto
          #- dulwich
          #- hieroglyph
          #- httpie
          #- mercurial
          #- passlib
          #- pip-tools
          #- psdash
          #- psutil
          #- requests
          #- see
          #- six
          #- uWSGI
