##################################################
# http://docs.ansible.com/user_module.html
# https://unix.stackexchange.com/questions/136894/command-line-method-or-programtically-add-ssh-key-to-github-com-user-account
---
- hosts: workstation

  tasks:
    - name: print from user
      debug: msg="in user.yml"

    - name: generate ssh key
      user: name=andor generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
    
    - name: Upload SSH Key
      command: curl -u "brianchoate" --data '{"title":"`echo ${USER}@``hostname`","key":"cat ~/.ssh/id_rsa.pub"}' https://api.github.com/user/keys


# EOF ############################################
