##################################################
# http://docs.ansible.com/user_module.html
---
- hosts: workstation

  tasks:
    - name: print from user
      debug: msg="in user.yml"

    - name: generate ssh key
      user: name=andor generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

# EOF ############################################
